POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jj@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "f23e0c58-23b3-48c3-8d6b-fe30c0666665"
}

### 

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "66607797-85a1-4492-9e78-47897d5c7f30",
	"account_id_to": "a4c59202-c51f-42c7-937e-ec0b4d438e82",
	"amount": 20
}

###

GET http://localhost:3003/balances/66607797-85a1-4492-9e78-47897d5c7f30 HTTP/1.1